### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [Gurylev/posthtml-each#3]
@fogrew Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by fogrew** [comment]
@Scrum thanks for your attention)

Once [I added the plugin to catalog](https://github.com/posthtml/posthtml-plugins/commit/d8d501f3c7ad9e1ad5366d5b2b2377c209e773a3), but later changed my nickname on the GitHub, so there is now an invalid link there.

Frankly, I developed it for fun and no longer interested in support it. It seems to me that the functionality of this plugin is too simple. But if you find it useful for the catalog, I can transfer the ownership of it to you.

Otherwise, I think I will archive the repository and mark it deprecated, so as not to mislead people anymore.

**Comment by Scrum** [comment]
@fogrew Hi

> Frankly, I developed it for fun and no longer interested in support it.

I think any of your packages has the right to life and development. 

> It seems to me that the functionality of this plugin is too simple.

The package should be simple)

> But if you find it useful for the catalog, I can transfer the ownership of it to you.

I will be happy to help develop your package

**Comment by fogrew** [comment]
> I will be happy to help develop your package

@Scrum I transferred repo. Thanks for your initiative! I will be glad if the development of this plugin continues without me.

**Comment by Scrum** [comment]
@fogrew Thank you, the transfer was successful, all rights and access to this package will also be available to you.

For full support, you need access from NPM

We will be happy to support your package.

**Comment by fogrew** [comment]
@Scrum new maintainer `scrum` invited to posthtml-each on npmjs.org ;-)

**Comment by Scrum** [comment]
@fogrew thanks 🎉
